### ISSUE TITLE
The simulation graphics looks blurry

### ISSUE THREAD

**Issue by XinghuiTao** [MicrosoftDocs/mslearn-mr-adt-in-unity#14]
![Screenshot (9)](https://user-images.githubusercontent.com/46446128/158846664-3e0ebc7d-41e5-45e9-b008-63fa0cc5edc4.png)

Everything runs smoothly~ however, the graphics in the simulation look very blurry. I think it must be to do with some settings when I import the Art, but I cannot figure out where they are. Can you help? Thanks!

**Comment by XinghuiTao** [comment]
BTW, when I scale up to maximum, it still looks blurry.

**Comment by adamlash** [comment]
Hey there! Thanks for going through the module.

Looking at your screenshot the first thing that does come to mind is the Scale setting in the Game Window. Check out this Stackoverflow thread for some suggestions on checking the Scale/Resolution to make sure everything is set correctly: https://stackoverflow.com/questions/49298386/sprites-quality-is-very-bad-in-game-window-in-unity

Let me know how it goes!

**Comment by adamlash** [comment]
Closing due to no reply
