### ISSUE TITLE
There are no package files to open unity project.

### ISSUE THREAD

**Issue by TakahiroMiyaura** [MicrosoftDocs/mslearn-mr-adt-in-unity#5]
Hi,

Thank you for providing the great project!
I've joined the build session!, and I really had a good time.

I try this project, but I guess that Not enough package files in this project.
Maybe I Guess that you set the required package using MR Feature Tool.
MR feature tool is update the manifest.json, and download package files(*.tgz). This project don't find these download files.
(usually, this files is  in Packages\MixedReality folder)

manifest.json is written the below:

```
{
  "scopedRegistries": [
    {
      "name": "Maps SDK for Unity",
      "scopes": [
        "com.microsoft.maps"
      ],
      "url": "https://unity.virtualearth.net/npm/registry/"
    }
  ],
  "dependencies": {
    "com.microsoft.maps.unity": "0.10.1",
    "com.microsoft.mixedreality.input": "file:MixedReality/com.microsoft.mixedreality.input-0.9.2006.tgz",
    "com.microsoft.mixedreality.openxr": "file:MixedReality/com.microsoft.mixedreality.openxr-0.9.5.tgz",
    "com.microsoft.mixedreality.toolkit.extensions": "file:MixedReality/com.microsoft.mixedreality.toolkit.extensions-2.6.1.tgz",
    "com.microsoft.mixedreality.toolkit.foundation": "file:MixedReality/com.microsoft.mixedreality.toolkit.foundation-2.6.1.tgz",
    "com.microsoft.mixedreality.toolkit.gpustats": "file:MixedReality/com.microsoft.mixedreality.toolkit.gpustats-1.0.3.tgz",
    "com.microsoft.mixedreality.toolkit.planefinding": "file:MixedReality/com.microsoft.mixedreality.toolkit.planefinding-1.0.0.tgz",
    "com.microsoft.mixedreality.toolkit.standardassets": "file:MixedReality/com.microsoft.mixedreality.toolkit.standardassets-2.6.1.tgz",
    "com.microsoft.spatialaudio.spatializer.unity": "file:MixedReality/com.microsoft.spatialaudio.spatializer.unity-1.0.196.tgz",
...
```
I guess that you may want to upload MixedReality folder, or change the step to use MR feature tool in Microsoft Learn.

![image](https://user-images.githubusercontent.com/8484268/119762933-91efc780-bee9-11eb-96f3-ea73db9ebf51.png)

Best regards

**Comment by JBrentJ** [comment]
Hey @TakahiroMiyaura, this is great feedback!  We will update the instructions.
